plugins {
    id "org.asciidoctor.jvm.convert" version "$asciidoctorJvmVersion"
    id "org.asciidoctor.jvm.pdf" version "$asciidoctorJvmVersion"
    id "org.asciidoctor.jvm.epub" version "$asciidoctorJvmVersion"
}

version = project.projectVersion
group = "org.grails.plugins"

apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.apache.grails.gradle.grails-plugin'
apply plugin: 'org.apache.grails.gradle.grails-gsp'

compileJava.options.release = 17

dependencies {
    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly "org.apache.grails:grails-dependencies-starter-web"

    // TODO: We need to make this configurable/pluggable
    compileOnly "org.apache.grails:grails-data-hibernate5"

    testCompileOnly "org.apache.grails:grails-testing-support-web"
}

grails {
    springDependencyManagement = false
}

bootJar.enabled = false

apply from: "${rootProject.projectDir}/gradle/docs.gradle"
